when:
  - event: push
  - event: pull_request

matrix:
  RUBY_VERSION:
    - 4.0
    - 3.4

steps:
    - name: build
      image: ruby:${RUBY_VERSION}-alpine
      commands:
        - apk add alpine-sdk yaml-dev
        - bundle install
        - rake
